Added isCaughtByPattern & caughtByPatterns
doctrine/lexer pull request #70
Opened 2022-11-03 09:49 UTC by AbdelkaderBah

- Tests

2022-11-03 15:19 UTC, AbdelkaderBah commented
I have created this Pull request because it is totally different (improved*) from the first one.
Also the new ```caughByPatters``` open the possibilty for ```getType``` to return ```array```
Do you consider adjusting return types to support arrays?

2022-11-04 10:11 UTC, AbdelkaderBah commented
There are some issues Coding Standards and Static analysis issues that I can correct. 

Can you please confirm that's all?

2022-11-04 10:12 UTC, AbdelkaderBah commented
@greg0ire @derrabus

2022-11-04 15:58 UTC, derrabus commented
Please don't ping people. We're doing this in our free-time and will perform a review when we have time to.

I can confirm that we do need a green CI for a merge and having all issues reported by our tooling fixed also helps with the review.

2022-11-04 19:42 UTC, greg0ire commented
> the first one

You should definitely link to it if you're not going to summarize what it was about.

2022-11-24 07:04 UTC, AbdelkaderBah commented
* I have fixed the styling
* I have improved the types
* I have provided a summary of this pull request in the first comment [#](https://github.com/doctrine/lexer/pull/70#issue-1434376068)

I apologize for pinging you previously, I am new to open source...

2022-11-24 07:33 UTC, AbdelkaderBah commented
P.S: This feature adds the possibility for ```isA``` to return an array, although this is not yet supported by the return type.

Do you think it will be okay to extend/amend the return type of ```isA``` or create a new public method(s)?

Example of possible usages:

![carbon (8)](https://user-images.githubusercontent.com/14665300/203720801-b33ffb03-da1f-4c64-a2cb-fed7bed9ca9f.png)

2022-11-24 08:26 UTC, AbdelkaderBah commented
I have improved the types of the newly introduced code. 
The workflows should now pass.

Can I please know which phpstan analyze level/config are you using?

2022-11-24 11:02 UTC, greg0ire commented
Yes, by taking a look at the configuration file:

https://github.com/doctrine/lexer/blob/6348c6170ec75073a5d97316e1da0a177ab49a61/phpstan.neon.dist#L2

2022-11-24 21:08 UTC, derrabus requested changes

2022-11-24 21:08 UTC, derrabus commented on .gitignore
> +/.idea
Please revert.

2022-11-24 21:08 UTC, derrabus commented on tests/Doctrine/Common/Lexer/CryptocurrencyAddressLexer.php
> +    protected function getCatchablePatterns()
```suggestion
    protected function getCatchablePatterns(): array
```

Please use native types when possible.

2022-11-24 21:08 UTC, derrabus commented on tests/Doctrine/Common/Lexer/CryptocurrencyAddressLexer.php
> +    protected function getNonCatchablePatterns()
```suggestion
    protected function getNonCatchablePatterns(): array
```

2022-11-24 21:08 UTC, derrabus commented on tests/Doctrine/Common/Lexer/CryptocurrencyAddressLexer.php
> +    protected function getType(&$value)
```suggestion
     */
    protected function getType(&$value): string
```

2022-11-24 21:08 UTC, derrabus commented on tests/Doctrine/Common/Lexer/CryptocurrencyAddressLexer.php
> +    protected function getTypes(&$value)
Where is this method called?

2022-11-24 21:11 UTC, derrabus commented
> P.S: This feature adds the possibility for `isA` & `getType` to return an array, although this is not yet supported by the return type.

This is a problem because callers won't expect an array here. And I also fail to understand why we would want an array here: Does that mean a token can have multiple types?

2022-11-24 22:33 UTC, greg0ire commented
Out of curiosity, is the cryptocurrency example you gave realistic? Unlike the ORM Lexer catchable patterns, all the patterns in the example match something that is grammatically similar: they are all addresses. Are you going to run into situations where replacing a bitcoin address with a litecoin address in a sentence will make the sentence syntactically invalid?

2022-11-24 22:35 UTC, greg0ire commented on lib/Doctrine/Common/Lexer/AbstractLexer.php
> +            if (! $this->isCaughtByPattern($value, $key)) {
It's weird that you don't get a static analysis warning here… what guarantees that `$key` is going to be a string? It usually is an integer.

2022-11-24 22:38 UTC, greg0ire commented on tests/Doctrine/Common/Lexer/CryptocurrencyAddressLexer.php
> +        return array_values($items)[0] ?? '';
:thinking: is returning an empty string really the appropriate thing to do here?

2022-11-25 13:27 UTC, AbdelkaderBah commented
> Out of curiosity, is the cryptocurrency example you gave realistic? Unlike the ORM Lexer catchable patterns, all the patterns in the example match something that is grammatically similar: they are all addresses. Are you going to run into situations where replacing a bitcoin address with a litecoin address in a sentence will make the sentence syntactically invalid?
> 
> If the example is not realistic, can you let us know what you are going to build from this in your personal projects? I'd like to understand what need prompted you to contribute this.

A **Bitcoin address in some cases can be a valid syntax for a Litecoin address** and vice versa
The example of regex I have provided is realistic but not accurate, The regex matches a sequence of characters but does not validate them. The example of addresses in the test provider is realistic and accurate.

The main reason that prompted me into contributing this feature, is that "getType" is not aware of the "pattern" that has been caught.

Declaration: at the moment I haven't used this library in any personal/work project, I am contributing for the sake of contributing to an open source.

2022-11-25 13:30 UTC, AbdelkaderBah commented
> > P.S: This feature adds the possibility for `isA` & `getType` to return an array, although this is not yet supported by the return type.
> 
> This is a problem because callers won't expect an array here. And I also fail to understand why we would want an array here: Does that mean a token can have multiple types?

**I think YES**, this example of cryptocurrency addresses proves it to me (A bitcoin address might have the same syntax as a Litecoin address). 
May I don't understand the principle lexer/tokenizer enough?

2022-11-25 19:01 UTC, greg0ire commented
> A Bitcoin address in some cases can be a valid syntax for a Litecoin address and vice versa

That's not really what I'm asking: I wasn't asking if a bitcoin address can be a valid litecoin address or vice versa, I already know that to be true from reading your tests.

This is a lexer, and my question is: will this extra information be useful to the parser? Does the parser need to be able to tell apart a litecoin address for a bitcoin address to tell if there is a syntax error or not?

> Declaration: at the moment I haven't used this library in any personal/work project, I am contributing for the sake of contributing to an open source.

While I appreciate your selflessness, I think contributing features and not using them might just result in feature creep. We need more than a theoretical need for this. Let's not build something because people might use it please :pray:

2022-11-25 20:57 UTC, AbdelkaderBah commented
> > A Bitcoin address in some cases can be a valid syntax for a Litecoin address and vice versa
> 
> That's not really what I'm asking: I wasn't asking if a bitcoin address can be a valid litecoin address or vice versa, I already know that to be true from reading your tests.
> 
> This is a lexer, and my question is: will this extra information be useful to the parser? Does the parser need to be able to tell apart a litecoin address for a bitcoin address to tell if there is a syntax error or not?
> 
> > Declaration: at the moment I haven't used this library in any personal/work project, I am contributing for the sake of contributing to an open source.
> 
> While I appreciate your selflessness, I think contributing features and not using them might just result in feature creep. We need more than a theoretical need for this. Let's not build something because people might use it please 🙏

My bet was on this use case:

![image](https://user-images.githubusercontent.com/14665300/204054213-2dc02536-2149-455b-955d-70f7a855db4c.png)

If it doesn't seem to describe the usefulness, Well, I guess I have failed to come up with a benefit that an end-user-land/parser might find useful.

2022-11-26 08:47 UTC, greg0ire commented
Well if you could demonstrate how this would benefit the parser of the ORM, I guess it would help: https://github.com/doctrine/orm/blob/2.13.x/lib/Doctrine/ORM/Query/Parser.php

Let's close this until you do.

2022-11-26 08:47 UTC, closed without merging