Modernize documentation code
doctrine/lexer pull request #73
Opened 2022-11-27 15:55 UTC by greg0ire

2022-11-27 15:56 UTC, greg0ire commented on docs/en/dql-parser.rst
This the sentence above says it looks "something like the following", I think it's OK, to make the ORM Lexer look more modern than it currently is.

2022-11-28 10:43 UTC, derrabus requested changes

2022-11-28 10:43 UTC, derrabus commented on docs/en/index.rst
> +    abstract protected function getCatchablePatterns(): array;
This code block mirrors the code from `AbstractLexer`. We should not add native types here until we've added them to `AbstractLexer` as well.

2022-11-28 10:43 UTC, derrabus commented on docs/en/simple-parser-example.rst
>              );
Let's modernize array constructors as well?

2022-11-28 13:07 UTC, derrabus approved these changes

2022-11-28 13:07 UTC, merged